//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMusic.Classes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistsInTracks
    {
        public int ID_artist { get; set; }
        public int ID_track { get; set; }
        public int ID_role { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Tracks Tracks { get; set; }
    }
}
