//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMusic.Classes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMusicEntities : DbContext
    {
        private static AMusicEntities context;

        public static AMusicEntities GetContext() {
            return context ?? (context = new AMusicEntities()); 
        }

        public AMusicEntities()
            : base("name=AMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SupportLog> SupportLog { get; set; }
        public virtual DbSet<Tracks> Tracks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ArtistsInTracks> ArtistsInTracks { get; set; }
        public virtual DbSet<FeaturedAlbums> FeaturedAlbums { get; set; }
        public virtual DbSet<FeaturedTracks> FeaturedTracks { get; set; }
    }
}
