//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMusic.Classes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportLog
    {
        public int ID_log { get; set; }
        public int ID_user { get; set; }
        public Nullable<System.DateTime> when_added { get; set; }
        public string content { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
